# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  portfolio:
    image: portfolio
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5046:5046
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
